language: ruby

services:
- docker

addons:
  apt:
    packages:
    - sshpass

script:
- "./build.sh $TRAVIS_BUILD_DIR"

before_deploy:
- ssh-keyscan -H $SSH_HOST 2>&1 | tee -a $HOME/.ssh/known_hosts

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh $TRAVIS_BUILD_DIR $SSH_HOST $SSH_USER
  on:
    branch: master

before_install:
- openssl aes-256-cbc -K $encrypted_c1f97256f233_key -iv $encrypted_c1f97256f233_iv
  -in travis_deploy.enc -out ./travis_deploy -d
- eval "$(ssh-agent -s)"
- chmod 600 ./travis_deploy
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./travis_deploy
