language: ruby

services:
- docker

addons:
  apt:
    packages:
    - sshpass

install:
- echo $SSH_PUBK >> $HOME/.ssh/known_hosts

script:
- ./build.sh

deploy:
  provider: script
  script: bash deploy.sh $SSH_HOST $SSH_USER $SSH_PASS
  on:
    branch: master
