language: ruby

services:
- docker

addons:
  apt:
    packages:
    - sshpass
script:
- ./build.sh $TRAVIS_BUILD_DIR

before_deploy:
- ssh-keyscan -H $SSH_HOST 2>&1 | tee -a $HOME/.ssh/known_hosts

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh $TRAVIS_BUILD_DIR $SSH_HOST $SSH_USER $SSH_PASS
  on:
    branch: master
