version: "3.2"

services:
  app:
    environment:
     - DEBUG=1
    ports:
     - 8080:80
    volumes:
     - .:/var/www/html

  composer:
    volumes:
     - .:/app

  npm:
    command: start
    volumes:
     - .:/app
