version: "3.2"

services:
  app:
    build: .
    volumes:
      - app:/var/www/html

  composer:
    image: composer
    volumes:
      - type: volume
        source: app
        target: /app

  npm:
    image: node:11.1
    entrypoint: npm
    command: build
    working_dir: /app
    volumes:
      - type: volume
        source: app
        target: /app

volumes:
  app:
