<footer>
    <section class="inner" id="findUs">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2515.1900013717764!2d-1.3907160845730067!3d50.920202179543!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487473e2435a31f7%3A0xf7a713798c7f8350!2sSt+Denys+Community+Centre!5e0!3m2!1sen!2suk!4v1453664151722" class="map" frameborder="0" style="border:0" allowfullscreen></iframe>

        <div class="schedule">
            <h2>Training Times</h2>
            <p>
            Monday: 7pm - 8:30pm (Everyone)<br/>
            Thursday: 7:15pm - 9pm (Juniors), 7:15pm - 10pm (18+)<br/>
            </p>
            <h2>Pricing</h2>
            <p>First two sessions are FREE</p>
            <p>Single session prices:</p>
            <ul>
                <li>Juniors: &pound;4</li>
                <li>Adults: &pound;5</li>
                <li>Junior Concession: &pound;3.50</li>
                <li>Adult Concession: &pound;4</li>
            </ul>
        </div>
    </section>

    <section class="inner">
        <div class="contact">
            <h2>Contact</h2>
            <div>
                St Denys Community Centre<br />
                    Priory Road<br />
                    St. Denys<br />
                    Southampton<br />
                    SO17 2JZ
            </div>
            <br/>
            <div>
                info@southamptonjitsu.com
            </div>
        </div>

        <div class="connect">
            <h2>Connect</h2>
            <ul class="social links">
                <li>
                    <a href="https://www.facebook.com/SouthamptonJitsuClub">
                        <img src="/images/icons/facebook.png" alt="Facebook" title="Facebook">
                    </a>
                    Facebook
                </li>
                <li>
                    <a href="https://twitter.com/jitsufoundation">
                        <img src="/images/icons/twitter.png" alt="Twitter" title="Twitter">
                    </a>
                    Twitter
                </li>
                <li>
                    <a href="https://www.youtube.com/user/thejitsufoundation">
                        <img src="/images/icons/youtube.png" alt="Youtube" title="Youtube">
                    </a>
                    YouTube
                </li>
            </ul>
        </div>

        <div class="footerTjf">
            <h2 title="Latest from The Jitsu Foundation">
                <a title="The Jitsu Foundation" href="https://www.jitsufoundation.org/">
                    <img src="/images/jitsu-foundation-logo.png" alt="Affiliated with The Jitsu Foundation" title="The Jitsu Foundation">
                </a>
            </h2>
            <?php echo $this->tjfTweet; ?>
        </div>
    </section>

    <div id="pageCopyright">
        &#169; 2019 Southampton Jitsu Club
    </div>
</footer>

