<footer>
    <div class="row">
        <div class="column large-3 contactDetails">
            <h2>Contact</h2>
            <div id="contactDetails_Address">

                <p>St Denys Community Centre<br />
                    Priory Road<br />
                    St. Denys<br />
                    Southampton<br />
                    SO17 2JZ</p>
            </div>
            <div>
                Email:&nbsp;info@southamptonjitsu.com
            </div>
        </div>
        <div class="column large-2">
            <h2>Spotlight</h2>
            <div class="column row">
                <p>
                    <span class="bold">First 2 Sessions FREE</span><br/>
                    Juniors: £4 <br/>
                    Adult: £5 <br/>
                </p>
            </div>
            <div class="column row">
                <p>
                    <span class="bold">Concessions</span><br/>
                    Students/Unwaged/Siblings <br/>
                    Junior £3.50; Adult £4<br/>
                </p>
            </div>
        </div>
        <div class="column large-5 footerTjf">
            <h2 title="Latest from The Jitsu Foundation">
                <a title="The Jitsu Foundation" href="https://www.jitsufoundation.org/">
                    <img src="/images/jitsu-foundation-logo.png" alt="Affiliated with The Jitsu Foundation" title="The Jitsu Foundation">
                </a>
            </h2>
            <?php echo $this->tjfTweet; ?>
        </div>
        <div class="column large-2">
            <h2>Connect</h2>
            <ul class="social links">
                <li>
                    <a href="https://www.facebook.com/SouthamptonJitsuClub">
                        <img src="/images/icons/facebook.png" alt="Facebook" title="Facebook">
                    </a>
                    Facebook
                </li>
                <li>
                    <a href="https://twitter.com/jitsufoundation">
                        <img src="/images/icons/twitter.png" alt="Twitter" title="Twitter">
                    </a>
                    Twitter
                </li>
                <li>
                    <a href="https://www.youtube.com/user/thejitsufoundation">
                        <img src="/images/icons/youtube.png" alt="Youtube" title="Youtube">
                    </a>
                    YouTube
                </li>
            </ul>
        </div>

    </div>
    </div>
    <div id="pageCopyright">
        &#169; 2016 Southampton Jitsu Club
    </div>
</footer>

