<section class="row">
    <div class="column large-12">
        <?php echo $this->introduction; ?>
    </div>
</section>

<article class="contentBlock">
    <div class="row">
        <div class="column large-12">
            <p class="x-large center">
                We look forward to seeing you on the mat!
            </p>
        </div>
    </div>
</article>

<article>
    <div class="row">
        <div class="column large-12">
            <?php echo $this->members; ?>
        </div>
    </div>
</article>

<script>
    $(document).ready(function() {
        $('.imageGallery').magnificPopup({
            delegate: 'a',
            type: 'image',
            closeOnContentClick: false,
            closeBtnInside: false,
            mainClass: 'mfp-with-zoom mfp-img-mobile',
            image: {
                verticalFit: true,
                titleSrc: function(item) {
                    return item.el.attr('title') + ' &middot; <a class="image-source-link" href="'+item.el.attr('data-source')+'" target="_blank">image source</a>';
                }
            },
            gallery: {
                enabled: true
            },
            zoom: {
                enabled: true,
                duration: 300, // don't foget to change the duration also in CSS
                opener: function(element) {
                    return element.find('img');
                }
            }

        });
    });
</script>
