<article>
    <div class="theArt">
        <h2>The Art</h2>
        <div class="copy">
            <?= $this->art; ?>
        </div>
        <div class="images">
            <img class="stretch" src="/images/nationals-group.png">
            <img src="/images/jitsu-foundation-logo.png">
            <img class="stretch" src="/images/summerball2.jpg">
        </div>
    </div>
</article>

<div class="clubLineup"></div>

<article>
    <h2>The Club</h2>
    <?= $this->club; ?>

    <h3>Who are we?</h3>
    <div class="staffProfiles large">
        <div class="profile">
            <img src="/images/avatars/jim-bass.png">
            <p>Jim Bass<br/>Club Instructor</p>
        </div>
        <div class="profile">
            <img src="/images/avatars/sarah-brennan.png">
            <p>Sarah Brennan<br/>Club Instructor</p>
        </div>
    </div>
    <? /*
    <div class="staffProfiles">
        <div class="profile">
            <img src="/images/avatar.png">
            <p>Clark Sirl</p>
        </div>
        <div class="profile">
            <img src="/images/avatar.png">
            <p>Justin Brennan</p>
        </div>
        <div class="profile">
            <img src="/images/avatar.png">
            <p>Rich Dean</p>
        </div>
        <div class="profile">
            <img src="/images/avatar.png">
            <p>Conor Dinning</p>
        </div>
    </div>
 */ ?>

    <h3>Frequently Asked Questions</h3>
    <h4>How much is it to train?</h4>
    <p>Your first two sessions are free, to allow you try the style to see if it is right for you. Standard fees are £5
        for adults and £4 for juniors (under 18s). Concessions for students and unwaged and family discounts are
        available, at £4 for adults and £3.50 for juniors.</p>

    <h4>Are there any restrictions on who can train?</h4>
    <p>We are a mixed club of male and female members and we welcome children age 10 and up. Many of our members are
        parents who train with their children. As long as you have a clean bill of health, we look forward to seeing you
        on the mat!</p>
    <p>If you have any specific requirements, feel free to drop us an email.</p>

    <h4>What equipment do I need?</h4>
    <p>All you need to do is turn up wearing tracksuit bottoms and a t-shirt and you will be able to start straight
        away! If you begin to train on a regular basis you will be expected to purchase a gi (the white pyjamas!) in
        which to train. These are available through the club as availability dictates, or from various sport
        retailers.</p>

    <h4>Can I bring family members?</h4>
    <p>Yes! Jiu Jitsu is definitely an activity you can do as a family, and many of our members are parents who train
        with children. We also offer a family discount. Drop us an email for more details.</p>

    <h3>Details</h3>
    <p><span class="bold">Address:</span><br/>
        St Denys Community Centre<br>
        Priory Road<br>
        St. Denys<br>
        Southampton<br>
        SO17 2JZ</p>

    <p><span class="bold">Email:</span>&nbsp;info@southamptonjitsu.com</p>
</article>
