<div id="topBar" class="hidden dynamic">
    <div id="mainNavContainer" class="inner">
        <span onclick="location.href = '/';" class="logo">
            <span id="southampton">Southampton</span> <span id="jitsu">Jiu Jitsu</span> <span id="club">Club</span>
        </span>

        <div class="mainNavigation">
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="/club">Club</a></li>
                <li><a href="/news">News</a></li>
            </ul>
        </div>
    </div>
</div>

    <div id="banner">
        <video playsinline id="topvideo" style="display:none;" crossorigin="anonymous" preload="auto" autoplay muted loop src=""></video>

        <header class="home">
            <div class="inner">

                <div id="bannerLogo">
                    <h1 class="logo">
                        <span id="southampton">Southampton</span> <span id="jitsu">Jiu Jitsu</span> <span id="club">Club</span>
                    </h1>
                </div>

                <div id="welcomeText">
                    <span class="blurb">
                        Mind.<br/>Body.<br/>Technique.
                    </span>
                    <p>Welcome to Southampton Jiu Jitsu, the friendliest self-defence club on the south coast for almost 15 years.</p>
                    <p>Try Jiu Jitsu today and get your first two sessions free.</p>
                    <p>Discounts are available for students.</p>
                </div>

            </div>
        </header>

        <span id="scrollIndicator"></span>
    </div>

    <section class="inner" id="homeSplash">
        <div class="splashbox strength">
            <div class="text">
                <span class="title">Strength</span>
                With Jiu Jitsu, you will see improvements in your fitness, co-ordination and posture, as well as general physical ability.
            </div>
        </div>
        <div class="splashbox skill">
            <div class="text">
                <span class="title">Skill</span>
                As well as applied situational awareness and self-defence skills, Jiu Jitsu nurtures your overall confidence and leadership ability.
            </div>
        </div>
        <div class="splashbox spirit">
            <div class="text">
                <span class="title">Spirit</span>
                Jiu Jitsu requires a focused, yet relaxed mindset; this makes it a great way to hone your self-discipline and concentration.
            </div>
        </div>
    </section>

    <section id="homeClubinfo">
        <div class="inner">
            <div class="copy">
                <h2>Who are Southampton Jiu Jitsu?</h2>
                <?=$this->copy;?>
                <a href="/club" class="infoButton">Find out more</a>
            </div>

        </div>
    </section>

    <section class="inner" id="home_news">
        <h2>Latest Club News</h2>
        <div class="newsItemWrap">
            <?=$this->article1;?>
        </div>
        <div class="newsItemWrap">
            <?=$this->article2;?>
        </div>

        <a href="/news" class="infoButton">Read more</a>
    </section>
<? /*
    <section class="inner">
        <h2>Upcoming Events</h2>
        <iframe src="https://calendar.google.com/calendar/embed?height=400&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=Europe%2FLondon&amp;src=OTNuNWkzNW1xdTRzZHVyOTI0czFuOTVyYmdAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%2330487E&amp;showTitle=0&amp;mode=AGENDA&amp;showDate=0&amp;showNav=0&amp;showTabs=0&amp;showPrint=0&amp;showCalendars=0&amp;showTz=0&amp;hl=en_GB" style="border-width:0" width="100%" height="400" frameborder="0" scrolling="no"></iframe>
    </section>

 */ ?>
