<header>
    <div class="container">
        <div id="bannerLogo">
            <h1 class="websiteTitle">
                <span id="southampton">Southampton</span> <span id="jitsu">Jiu Jitsu</span> <span id="club">Club</span>
            </h1>
        </div>
    </div>
</header>

<script>
    var images = [];
    images.push('/images/home/11838844_1681415315426002_7943262589252491928_o.jpg');
    images.push('/images/home/11807186_1681415108759356_2012583516355331398_o.jpg');
    images.push('/images/home/11864864_1686734318227435_7395144794963996504_o.jpg');
    images.push('/images/home/12232709_10154371401844488_4064204128653645885_o.jpg');
    images.push('/images/home/12247931_10154368627714488_1818566135957547328_o.jpg');
    $('header').backstretch(images, {duration: 5000, fade: 750});
</script>

<main>
    <section markdown="1" class="row" id="homeCopyContainer">
        <div class="column large-12" id="homeCopy">
            <?php echo $this->copy; ?>
        </div>
    </section>

    <section id="home_news" class="row">
        <div class="column large-12">
            <h2>Latest Club News</h2>

            <div class="row">
                <div class="column large-6">
                    <?php echo $this->article1; ?>
                </div>
                <div class="column large-6">
                    <?php echo $this->article2; ?>
                </div>
            </div>
        </div>
    </section>

    <section class="row">
        <div class="column large-4"><div class="iframe_responsive">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2515.1900013717764!2d-1.3907160845730067!3d50.920202179543!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487473e2435a31f7%3A0xf7a713798c7f8350!2sSt+Denys+Community+Centre!5e0!3m2!1sen!2suk!4v1453664151722" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div></div>
        <div class="column large-4" markdown="1">
            <h2>Where to find us</h2>

            <p>St Denys Community Centre<br />
                Priory Road<br />
                St. Denys<br />
                Southampton<br />
                SO17 2JZ</p>
        </div>
        <div class="column large-4" markdown="1">

            <p><strong>Monday</strong><br />
                1900-2030 (Junior)<br />
                1900-2030 (Adult)</p>
            <p><strong>Thursday</strong><br />
                1915-2100 (Junior)<br />
                1915-2130 (Adult)</p>
        </div>
    </section>
</main>
