<!DOCTYPE html>
<html lang="en">
<head>
    <link href="/dist/css/new.css" type="text/css" rel="stylesheet" />
    <script src="/dist/js/new.js" type="text/javascript"></script>
<!--    <script src="/dist/js/main.js" type="text/javascript"></script>-->

    <style>
    </style>
</head>
<body>
    <div id="banner">
        <video id="topvideo" style="display:none;" crossorigin="anonymous" preload="auto" autoplay muted loop src=""></video>

        <div id="topBar" style="display: none;">
            <div class="inner">
                <div class="logo">
                    <span id="southampton">Southampton</span>
                    <span id="jitsu">Jiu Jitsu</span>
                    <span id="club">Club</span>
                </div>
            </div>
        </div>

        <header>
            <div class="inner">

                <div id="bannerLogo">
                    <h1 class="logo">
                        <span id="southampton">Southampton</span> <span id="jitsu">Jiu Jitsu</span> <span id="club">Club</span>
                    </h1>
                </div>

                <div id="welcomeText">
                    <span class="blurb">
                        Technique //<br/>Body // Mind
                    </span>
<!--                            <p>Improve your fitness; nurture your confidence; hone your self-discipline. Welcome to the friendliest self-defence training club on the south coast.</p>-->

                    <p>Welcome to Southampton Jiu Jitsu, the friendliest self-defence club on the south coast for almost 15 years.</p>
                    <p>Try Jiu Jitsu today and get your first two sessions free.</p>
                    <p>Discounts are available for students.</p>
<!--                            <p>Two sessions free, discounts available for students.</p>-->


                </div>

            </div>
        </header>

        <span id="scrollIndicator"></span>
    </div>


    <section class="inner" id="home_news">
        <h2>Latest Club News</h2>
            <div class="newsItemWrap">
                <div class="newsItem" data-url="/news/2019-10-22-junior-atemis" style="background-image: url(/images/news/2019-junior-atemis/thumbnail.JPG);" onclick="location.href = this.getAttribute('data-url');">
                    <h3>2019 Junior Atemis</h3>
                </div>
            </div>
            <div class="newsItemWrap">
                <div class="newsItem" data-url="/news/2019-07-06-summer-ball" style="background-image: url(/images/news/2019-07-06-summer-ball.jpg);" onclick="location.href = this.getAttribute('data-url');">
                    <h3>TJJF Summer Ball</h3>
                </div>
            </div>
    </section>

    <section class="grey">
        <div class="inner">
        <h2>Who are Southampton Jiu Jitsu?</h2>
            <p>Founded in March 2005 by Sensei Jim Bass, Southampton Jitsu Club is the friendliest self-defence training club on the south coast.</p>
            <p>We train twice a week, all year round. All you need to do is turn up wearing tracksuit bottoms and a t-shirt and you will be able to start straight away! We are an official club of The Jiu Jitsu Foundation (TJJF) and regularly attend regional and national events, from the national championships to the yearly celebratory Summer Ball. There are also numerous social events, and our members will usually be found after sessions unwinding with a drink!</p>
            <p>Your first two sessions are free, to allow you to try Jitsu without any commitment to see if the art is what you want to do. If you have any questions, feel free to drop us an <a href="#">email</a> or visit our <a href="#">Frequently Asked Questions</a>.</p>


<!--        <p>The club was founded by Sensei Jim Bass, and in December 2014 Sensei James Payne took over as the lead instructor. We are an official club of The Jiu Jitsu Foundation (TJJF), and as such regularly attend regional and national events, from the national championships to the yearly celebratory Summer ball. There are also numerous ad-hoc social events, and our members will usually be found unwinding with a drink after sessions!</p>-->
<!---->
<!--        <p>We train twice a week, all year round. All you need to do is turn up wearing tracksuit bottoms and a t-shirt and you will be able to start straight away! Our members are of all ages, and we welcome children from ages 10 and up. Many of our members are parents who train with their children; Jitsu is definitely an activity you can do as a family! Your first two sessions are free, to allow you to try Jitsu without any commitment to see if the art is what you want to do, and if our style and methods of teaching and training are right for you.</p>-->
<!---->
<!--        <p>If you have any questions, feel free to drop us an email.</p>-->
        </div>
    </section>
</body>
</html>
