<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <link rel="icon" type="image/png" href="/images/favicon.png">
    <link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon" />
    <link rel="apple-touch-icon" href="/images/apple-touch-icon.png" />
    <link rel="apple-touch-icon" sizes="57x57" href="/images/apple-touch-icon-57x57.png" />
    <link rel="apple-touch-icon" sizes="72x72" href="/images/apple-touch-icon-72x72.png" />
    <link rel="apple-touch-icon" sizes="76x76" href="/images/apple-touch-icon-76x76.png" />
    <link rel="apple-touch-icon" sizes="114x114" href="/images/apple-touch-icon-114x114.png" />
    <link rel="apple-touch-icon" sizes="120x120" href="/images/apple-touch-icon-120x120.png" />
    <link rel="apple-touch-icon" sizes="144x144" href="/images/apple-touch-icon-144x144.png" />
    <link rel="apple-touch-icon" sizes="152x152" href="/images/apple-touch-icon-152x152.png" />
    <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-180x180.png" />

    <title>Home | Southampton Jitsu Club</title>

    <link href="/dist/css/main.css" type="text/css" rel="stylesheet" />
    <script src="/dist/js/main.js" type="text/javascript"></script>
</head>

<body class="">
<div id="topBar">
    <div class="row">
        <div id="logoContainer">
            <h1 onclick="location.href = '/';" class="websiteTitle">
                <span id="southampton">Southampton</span> <span id="jitsu">Jiu Jitsu</span> <span id="club">Club</span>
            </h1>
        </div>
    </div>
</div>

<div class="nav-mobile"></div>
<nav style="">
    <ul>
        <li class="homeLink">
            <a href="/">
                Home
            </a>
        </li>
        <li>
            <a href="/art">
                The Art
            </a>
        </li>
        <li>
            <a href="/club">
                The Club
            </a>
        </li>
        <li>
            <a href="/news">
                News
            </a>
        </li>
        <li>
            <a href="/pricing">
                Pricing &amp; Membership
            </a>
        </li>
        <li>
            <a href="/contact">
                Contact
            </a>
        </li>
    </ul>
</nav>


<?php echo $this->content; ?>

<?php echo $this->footer; ?>

</body>
</html>
