<div id="topBar">
    <div id="mainNavContainer" class="inner">
        <span onclick="location.href = '/';" class="logo">
            <span id="southampton">Southampton</span> <span id="jitsu">Jiu Jitsu</span> <span id="club">Club</span>
        </span>

        <div class="mainNavigation">
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="/club">Club</a></li>
                <li><a href="/news">News</a></li>
            </ul>
        </div>
    </div>
</div>

<section class="copy">
    <div class="inner">
        <?php echo $this->copy; ?>
    </div>
</section>

