<header style="height:20em">
    <div style="position:absolute;
             top:0;
             right:0;
             left:0;
             bottom:0;
             width:100%;
             height:100%;
             background-image: url(http://grav-test.local/user/themes/jitsu/images/transparent-medium.png);">
    </div>
    <div class="row">
        <h1>
            <?php echo $this->title; ?>
        </h1>
    </div>
</header>

<main>
    <?php echo $this->copy; ?>
</main>

