<div
        class="newsItem <?=(isset($this->url) ? 'link' : '')?>"
        <?=(isset($this->url) ? "data-url=\"{$this->url}\" onclick=\"location.href = this.getAttribute('data-url');\"" : '')?>
        style="<?php echo (!isset($this->imageUrl) ? '' : "background-image: url({$this->imageUrl});"); ?>"
>
    <h3><?=$this->title?></h3>

<!--    <div style="position: absolute; top: 0; left: 0; bottom: 0; right: 0; width: 100%; height: 100%; background-color: red">-->
<!--        <div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/345329983?title=0&byline=0&portrait=0" style="position:absolute;top:0;left:0;width:100%;height:100%;" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>-->
<!--    </div>-->

    <div class="content">
        <?=$this->content?>
    </div>
</div>